name: 🗳️ Daily Google-Form Vote

on:
  # allow manual runs from the Actions UI
  workflow_dispatch:

  # still run daily at 12:00 UTC (8 AM Eastern Daylight Time)
  schedule:
    - cron: '0 12 * * *'

jobs:
  vote_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Install Chrome & ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Run vote bot
        env:
          CHROMEDRIVER_PATH: /usr/bin/chromedriver
        run: python vote_bot.py
